/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 shining_star.gltf --transform
Author: vodkaavocado (https://sketchfab.com/vodkaavocado)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shining-star-low-poly-72e462e4946b4bbb9a6c18e876f04784
Title: Shining star low poly
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/shining_star-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} scale={0.918} />
    </group>
  )
}

useGLTF.preload('/shining_star-transformed.glb')
