/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 apple_macbook_air_15_space_gray2023.gltf --transform
Author: akshatmittal (https://sketchfab.com/akshatmittal)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-macbook-air-15-space-gray-2023-e8d82e341c794141a2561c2c9d01d79e
Title: Apple Macbook Air 15 (Space Gray) 2023
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'


export default function Model(props) {
  const { nodes, materials } = useGLTF('/apple_macbook_air_15_space_gray2023-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.xVreGKoBGSZYMij.geometry} material={materials.dKLyhhkbEyMrqky} scale={0.01} />
      <mesh geometry={nodes.CTBERffHyoCSDBm_0.geometry} material={materials.YjmXmicdBWsFQyD} scale={0.01} />
      <mesh geometry={nodes.hczGzWOWpedUDYd_0.geometry} material={materials.pEUnNAGXCoAFoUk} scale={0.01} />
      <mesh geometry={nodes.biHEvGDNnTqamRb.geometry} material={materials.dFfswgailNMtaYj} scale={0.01} />
      <mesh geometry={nodes.TyOrApjEOLhYCaF.geometry} material={materials.AZirwHJdxxcChtp} scale={0.01} />
      <mesh geometry={nodes.vrIckaCELZpnnNK.geometry} material={materials.dkOmcmuFedorUKC} scale={0.01} />
      <mesh geometry={nodes.SadnAkehSlxIwKv.geometry} material={materials.VNZklasZKSWjWUk} scale={0.01} />
      <mesh geometry={nodes.OrhpMXCxeprcNok.geometry} material={materials.OfvrpEsWzbOpbcs} scale={0.01} />
      <mesh geometry={nodes.aLWGnOLpsFWVSfy.geometry} material={materials.iFCKstMLETFqCmZ} scale={0.01} />
      <mesh geometry={nodes.WDUVUVPpNjdIPkb.geometry} material={materials.ZPlxrBOYjSNYvVB} scale={0.01} />
      <mesh geometry={nodes.NqUinIWcwSlXpvt.geometry} material={materials.rvYnnyqXrbFJXxh} scale={0.01} />
      <mesh geometry={nodes.MaufYfIBnxcfRgH.geometry} material={materials.SsSIPrCyVNTOxvd} scale={0.01} />
      <mesh geometry={nodes.HrtjMXqDCcINmDE_0.geometry} material={materials.BfIgIOaUEgyoEft} scale={0.01} />
      <mesh geometry={nodes.zWqVyCKpTAuZNiu_0.geometry} material={materials.zFJMMvikHFjtmzd} scale={0.01} />
      <mesh geometry={nodes.MYVKQTLmUkzzlBj_0.geometry} material={materials.jIhmcgKbjDOICsY} scale={0.01} />
      <mesh geometry={nodes.qEJjkxdFZFWJWzR_0.geometry} material={materials.JKvAHnqjqlqshmY} scale={0.01} />
      <mesh geometry={nodes.eeWSraIVipLsSmX_0.geometry} material={materials.JKvAHnqjqlqshmY} scale={0.01} />
      <mesh geometry={nodes.PgbYkhvRdcmMeGL.geometry} material={materials.wOIDWopwzKBeTNU} scale={0.01} />
      <mesh geometry={nodes.rktWdhtZkCSmqne.geometry} material={materials.ZrrjpMZNDbttBCc} scale={0.01} />
      <mesh geometry={nodes.HHcJitDCPTdgnFk.geometry} material={materials.RMDHOHZakhhXXHT} scale={0.01} />
      <mesh geometry={nodes.KgPDMIRPrxAynTV.geometry} material={materials.hZBlDyddxAQhuPm} scale={0.01} />
      <mesh geometry={nodes.BkHyotPbPWzwAAj.geometry} material={materials.sRPrqogRtliLLae} scale={0.01} />
      <mesh geometry={nodes.ebZHPVwKTmqvgbU.geometry} material={materials.kDpbvvjwMgCSCmF} scale={0.01} />
      <mesh geometry={nodes.uSnVzUkbvcGaVtm.geometry} material={materials.AqVxlXuHIFahLKs} scale={0.01} />
      <mesh geometry={nodes.tIZmzvOOHrlOFci.geometry} material={materials.oKQWdLrXUCbYByI} scale={0.01} />
      <mesh geometry={nodes.UmfOhraHkqkMHJr.geometry} material={materials.OFvWomWIIUgmKKA} scale={0.01} />
      <mesh geometry={nodes.JoRHkRchuIHZFdI.geometry} material={materials.mEMAJQfiigHeUXV} scale={0.01} />
      <mesh geometry={nodes.juMIjHdkYweLlGP.geometry} material={materials.NzmRSNqyvNKhkmK} scale={0.01} />
      <mesh geometry={nodes.zNYAavJLMZZchIX.geometry} material={materials.ASadxrcBIAXFnLn} scale={0.01} />
      <mesh geometry={nodes.CkZgGMshUOhytMM.geometry} material={materials.AvocVUvikCzzMtu} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/apple_macbook_air_15_space_gray2023-transformed.glb')
