/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 iphone_14_pro.gltf --transform
Author: Tycho Magnetic Anomoly (https://sketchfab.com/CitrixStorm2222)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/iphone-14-pro-9eb757e57f8744748e286f4078367fec
Title: Iphone 14 Pro
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/iphone_14_pro-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.BASE} position={[0.386, 0.022, 0.628]} scale={[0.607, 0.843, 0.041]} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.FRONT} position={[0.386, 0.022, 0.628]} scale={[0.607, 0.843, 0.041]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.SIDE} position={[0.386, 0.022, 0.628]} scale={[0.607, 0.843, 0.041]} />
    </group>
  )
}

useGLTF.preload('/iphone_14_pro-transformed.glb')
