/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 abstract_design.gltf --transform
Author: pdeep4494 (https://sketchfab.com/pdeep4494)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/abstract-design-7bf3e607b7b9466488fdab9854b4cbbb
Title: Abstract Design
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/abstract_design-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Torus_Material001_0.geometry} material={materials['Material.001']} rotation={[-1.576, -Math.PI / 2, 0]} scale={0.783} />
    </group>
  )
}

useGLTF.preload('/abstract_design-transformed.glb')
