/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 laptop_1.gltf --transform
Author: GeniusPilot2016 (https://sketchfab.com/GeniusPilot2016)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laptop-f69d66e7a3404a6b91d59882409097ab
Title: Laptop
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/laptop_1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.body} position={[0.498, 0.016, 0.416]} rotation={[-0.027, 0, 0]} scale={0.281} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.black_plastic} position={[0.498, 0.016, 0.416]} rotation={[-0.027, 0, 0]} scale={0.281} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.touchpad} position={[0.498, 0.016, 0.416]} rotation={[-0.027, 0, 0]} scale={0.281} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.holes} position={[0.498, 0.016, 0.416]} rotation={[-0.027, 0, 0]} scale={0.281} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.ports} position={[0.498, 0.016, 0.416]} rotation={[-0.027, 0, 0]} scale={0.281} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.metal} position={[0.498, 0.016, 0.416]} rotation={[-0.027, 0, 0]} scale={0.281} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.speaker} position={[0.498, 0.016, 0.416]} rotation={[-0.027, 0, 0]} scale={0.281} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.display} position={[0.498, 0.037, 0.667]} rotation={[1.806, 0, 0]} scale={0.281} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.touchscreen_bezel} position={[0.498, 0.037, 0.667]} rotation={[1.806, 0, 0]} scale={0.281} />
    </group>
  )
}

useGLTF.preload('/laptop_1-transformed.glb')
